---
- name: "Install core OPA packages"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "opa-basic-tools"
    - "rdma-core"

- name: "Install additional IB diagnostic utils"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "infiniband-diags"
    - "ibutils"
